on:
  pull_request:
    types: [opened, reopened]

jobs:
  rotate-test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewers: "HurSungYun,HurSungYun"
